name: Sync shadow beacon

on:
  schedule:
    - cron: "*/30 * * * *"
  push:
    branches:
      - main

jobs:
  shadow-beacon:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Cache build state
        id: cache-build-state
        uses: actions/cache@v3
        with:
          path: ./out
          key: ${{ runner.os }}

      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}

      - name: Cache build cache
        id: cache-build-cache
        uses: actions/cache@v3
        with:
          path: ./cache
          key: ${{ runner.os }}

      - uses: actions/setup-node@v2
      - name: Install dev dependencies
        run: yarn install

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Sync beacon
        run: forge script SyncShadowBeacon --chain-id 1 --broadcast
        env:
          GOERLI_RPC_URL: ${{ secrets.GOERLI_RPC_URL }}
          MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
          MUMBAI_RPC_URL: ${{ secrets.MUMBAI_RPC_URL }}
          POLYGON_RPC_URL: ${{ secrets.POLYGON_RPC_URL }}
          SHADOW_BEACON_RELAY_PRIVATE_KEY: ${{ secrets.SHADOW_BEACON_RELAY_PRIVATE_KEY }}
